---

- hosts: rabbitmq
  roles:
    - erlang
    - geerlingguy.rabbitmq
    - rabbitmq-cookie

- hosts: rabbitmq-slave
  roles:
    - erlang
    - geerlingguy.rabbitmq
    - rabbitmq-cookie
    - rabbitmq-slave
