---
# tasks file for rabbitmq-config

- name: Copy RabbitMQ Erlang Cookie
  template:
    src: "{{ role_path }}/templates/erlang.cookie"
    dest: /var/lib/rabbitmq/.erlang.cookie

- name: Restart RabbitMQ
  service:
    name: rabbitmq-server.service
    state: restarted

- name: Enable management
  command: rabbitmq-plugins enable rabbitmq_management